[package]
name = "l337"
version = "0.1.0"
authors = ["Jonathon Sheffield <samsmug@gmail.com>", "Joe Wilm <joe@jwilm.com>"]
license = "MIT OR Apache-2.0"
description = "yet another connection pooler"
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"
crossbeam = "0.4"
failure = "0.1"
log = "0.4"

[workspace]
members = [
  "l337-postgres",
  "l337-redis"
]
